# Generated by Django 4.1.7 on 2023-03-31 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ig', '0002_remove_user_is_acrive_user_bio_alter_user_is_active'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
